/* automatically generated by rust-bindgen 0.59.2 */

extern "C" {
    pub fn io_init();
}
extern "C" {
    pub fn io_sethandler_common(
        base: u16,
        size: libc::c_int,
        inb: ::std::option::Option<unsafe extern "C" fn(addr: u16, priv_: *mut libc::c_void) -> u8>,
        inw: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, priv_: *mut libc::c_void) -> u16,
        >,
        inl: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, priv_: *mut libc::c_void) -> u32,
        >,
        outb: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, val: u8, priv_: *mut libc::c_void),
        >,
        outw: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, val: u16, priv_: *mut libc::c_void),
        >,
        outl: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, val: u32, priv_: *mut libc::c_void),
        >,
        priv_: *mut libc::c_void,
        step: libc::c_int,
    );
}
extern "C" {
    pub fn io_removehandler_common(
        base: u16,
        size: libc::c_int,
        inb: ::std::option::Option<unsafe extern "C" fn(addr: u16, priv_: *mut libc::c_void) -> u8>,
        inw: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, priv_: *mut libc::c_void) -> u16,
        >,
        inl: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, priv_: *mut libc::c_void) -> u32,
        >,
        outb: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, val: u8, priv_: *mut libc::c_void),
        >,
        outw: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, val: u16, priv_: *mut libc::c_void),
        >,
        outl: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, val: u32, priv_: *mut libc::c_void),
        >,
        priv_: *mut libc::c_void,
        step: libc::c_int,
    );
}
extern "C" {
    pub fn io_handler_common(
        set: libc::c_int,
        base: u16,
        size: libc::c_int,
        inb: ::std::option::Option<unsafe extern "C" fn(addr: u16, priv_: *mut libc::c_void) -> u8>,
        inw: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, priv_: *mut libc::c_void) -> u16,
        >,
        inl: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, priv_: *mut libc::c_void) -> u32,
        >,
        outb: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, val: u8, priv_: *mut libc::c_void),
        >,
        outw: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, val: u16, priv_: *mut libc::c_void),
        >,
        outl: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, val: u32, priv_: *mut libc::c_void),
        >,
        priv_: *mut libc::c_void,
        step: libc::c_int,
    );
}
extern "C" {
    pub fn io_sethandler(
        base: u16,
        size: libc::c_int,
        inb: ::std::option::Option<unsafe extern "C" fn(addr: u16, priv_: *mut libc::c_void) -> u8>,
        inw: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, priv_: *mut libc::c_void) -> u16,
        >,
        inl: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, priv_: *mut libc::c_void) -> u32,
        >,
        outb: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, val: u8, priv_: *mut libc::c_void),
        >,
        outw: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, val: u16, priv_: *mut libc::c_void),
        >,
        outl: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, val: u32, priv_: *mut libc::c_void),
        >,
        priv_: *mut libc::c_void,
    );
}
extern "C" {
    pub fn io_removehandler(
        base: u16,
        size: libc::c_int,
        inb: ::std::option::Option<unsafe extern "C" fn(addr: u16, priv_: *mut libc::c_void) -> u8>,
        inw: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, priv_: *mut libc::c_void) -> u16,
        >,
        inl: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, priv_: *mut libc::c_void) -> u32,
        >,
        outb: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, val: u8, priv_: *mut libc::c_void),
        >,
        outw: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, val: u16, priv_: *mut libc::c_void),
        >,
        outl: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, val: u32, priv_: *mut libc::c_void),
        >,
        priv_: *mut libc::c_void,
    );
}
extern "C" {
    pub fn io_handler(
        set: libc::c_int,
        base: u16,
        size: libc::c_int,
        inb: ::std::option::Option<unsafe extern "C" fn(addr: u16, priv_: *mut libc::c_void) -> u8>,
        inw: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, priv_: *mut libc::c_void) -> u16,
        >,
        inl: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, priv_: *mut libc::c_void) -> u32,
        >,
        outb: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, val: u8, priv_: *mut libc::c_void),
        >,
        outw: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, val: u16, priv_: *mut libc::c_void),
        >,
        outl: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, val: u32, priv_: *mut libc::c_void),
        >,
        priv_: *mut libc::c_void,
    );
}
extern "C" {
    pub fn io_sethandler_interleaved(
        base: u16,
        size: libc::c_int,
        inb: ::std::option::Option<unsafe extern "C" fn(addr: u16, priv_: *mut libc::c_void) -> u8>,
        inw: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, priv_: *mut libc::c_void) -> u16,
        >,
        inl: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, priv_: *mut libc::c_void) -> u32,
        >,
        outb: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, val: u8, priv_: *mut libc::c_void),
        >,
        outw: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, val: u16, priv_: *mut libc::c_void),
        >,
        outl: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, val: u32, priv_: *mut libc::c_void),
        >,
        priv_: *mut libc::c_void,
    );
}
extern "C" {
    pub fn io_removehandler_interleaved(
        base: u16,
        size: libc::c_int,
        inb: ::std::option::Option<unsafe extern "C" fn(addr: u16, priv_: *mut libc::c_void) -> u8>,
        inw: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, priv_: *mut libc::c_void) -> u16,
        >,
        inl: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, priv_: *mut libc::c_void) -> u32,
        >,
        outb: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, val: u8, priv_: *mut libc::c_void),
        >,
        outw: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, val: u16, priv_: *mut libc::c_void),
        >,
        outl: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, val: u32, priv_: *mut libc::c_void),
        >,
        priv_: *mut libc::c_void,
    );
}
extern "C" {
    pub fn io_handler_interleaved(
        set: libc::c_int,
        base: u16,
        size: libc::c_int,
        inb: ::std::option::Option<unsafe extern "C" fn(addr: u16, priv_: *mut libc::c_void) -> u8>,
        inw: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, priv_: *mut libc::c_void) -> u16,
        >,
        inl: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, priv_: *mut libc::c_void) -> u32,
        >,
        outb: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, val: u8, priv_: *mut libc::c_void),
        >,
        outw: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, val: u16, priv_: *mut libc::c_void),
        >,
        outl: ::std::option::Option<
            unsafe extern "C" fn(addr: u16, val: u32, priv_: *mut libc::c_void),
        >,
        priv_: *mut libc::c_void,
    );
}
extern "C" {
    pub fn inb(port: u16) -> u8;
}
extern "C" {
    pub fn outb(port: u16, val: u8);
}
extern "C" {
    pub fn inw(port: u16) -> u16;
}
extern "C" {
    pub fn outw(port: u16, val: u16);
}
extern "C" {
    pub fn inl(port: u16) -> u32;
}
extern "C" {
    pub fn outl(port: u16, val: u32);
}
extern "C" {
    pub fn io_trap_add(
        func: ::std::option::Option<
            unsafe extern "C" fn(
                size: libc::c_int,
                addr: u16,
                write: u8,
                val: u8,
                priv_: *mut libc::c_void,
            ),
        >,
        priv_: *mut libc::c_void,
    ) -> *mut libc::c_void;
}
extern "C" {
    pub fn io_trap_remap(handle: *mut libc::c_void, enable: libc::c_int, addr: u16, size: u16);
}
extern "C" {
    pub fn io_trap_remove(handle: *mut libc::c_void);
}
