#![allow(non_camel_case_types, non_snake_case, dead_code)]
/* automatically generated by rust-bindgen 0.59.2 */

extern "C" {
    pub(crate) fn random_generate() -> u8;
}
extern "C" {
    pub(crate) fn random_init();
}
